version: "3.9"  # optional since v1.27.0
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JUPYTER_TOKEN=go
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work 
  
volumes:
  attention: 
   